# Generated by Django 4.1.5 on 2023-01-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(upload_to="profile_pictures/"),
        ),
    ]
